services:
  # nginx:
  #   build: ./nginx
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - internal
  #   volumes:
  #     - /data/nginx/vhosts:/etc/nginx/conf.d/vhosts
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Roteador para o dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    networks:
      - internal

  database:
    build: ./database
    image: mariadb:10.11
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal

  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch:2.3.4
    container_name: elasticsearch
    environment:
      - CLUSTER_NAME=edirectory-cluster
      - NODE_NAME=node-1
      - ES_HEAP_SIZE=512m
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: 123456789
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - internal

  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    environment:
      CEREBRO_PORT: 9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cerebro.rule=Host(`cerebro.localhost`)"
      - "traefik.http.routers.cerebro.entrypoints=web"
      - "traefik.http.services.cerebro.loadbalancer.server.port=9000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    name: internal
